const toeicQuestions = {
    office: [
        { id: 1, question: "The marketing team needs to (  ) the presentation for the board meeting.", options: ["A. finalize", "B. finally", "C. final", "D. finalized"], correct: 0, explanation: "finalize 是动词，意为“完成/敲定”。这里需要动词原形接在 needs to 后面。" },
        { id: 2, question: "Please submit your expense report by the end of the (  ).", options: ["A. fiscal", "B. fish", "C. feature", "D. factor"], correct: 0, explanation: "fiscal year/month 意为“财年/财月”。" },
        { id: 3, question: "The CEO decided to (  ) the company's expansion plans.", options: ["A. defer", "B. different", "C. defeat", "D. defect"], correct: 0, explanation: "defer 意为“推迟”。" },
        { id: 4, question: "We have (  ) several candidates for the position of manager.", options: ["A. interviewed", "B. interested", "C. intended", "D. inventoried"], correct: 0, explanation: "interview candidates 意为“面试候选人”。" },
        { id: 5, question: "Employees are expected to (  ) with the new safety regulations.", options: ["A. comply", "B. combine", "C. compile", "D. complete"], correct: 0, explanation: "comply with 意为“遵守”。" },
        { id: 6, question: "The (  ) for the seminar will be distributed tomorrow.", options: ["A. agenda", "B. agent", "C. agency", "D. age"], correct: 0, explanation: "agenda 意为“议程”。" },
        { id: 7, question: "Could you (  ) me on the progress of the project?", options: ["A. update", "B. upload", "C. upcoming", "D. uptight"], correct: 0, explanation: "update sb on sth 意为“向某人同步最新进展”。" },
        { id: 8, question: "The company offers a (  ) benefits package to its staff.", options: ["A. comprehensive", "B. compressed", "C. complicated", "D. component"], correct: 0, explanation: "comprehensive benefits 意为“全面的福利”。" },
        { id: 9, question: "We need to reach a (  ) before moving forward.", options: ["A. consensus", "B. consent", "C. consequence", "D. conscious"], correct: 0, explanation: "reach a consensus 意为“达成共识”。" },
        { id: 10, question: "The office will be (  ) starting next Monday for renovations.", options: ["A. closed", "B. closing", "C. close", "D. closure"], correct: 0, explanation: "be closed 意为“关闭状态”。" },
        { id: 11, question: "The manager decided to (  ) the meeting until todos are completed.", options: ["A. adjourn", "B. join", "C. adjust", "D. admit"], correct: 0, explanation: "adjourn 意为“使延期/休会”。" },
        { id: 12, question: "She has been (  ) to the position of Senior Director.", options: ["A. promoted", "B. prompt", "C. prohibited", "D. provided"], correct: 0, explanation: "be promoted to 意为“被晋升到……职位”。" },
        { id: 13, question: "Please (  ) the attached document for more details.", options: ["A. review", "B. reveal", "C. revolve", "D. reverse"], correct: 0, explanation: "review 意为“检查/复查”。" },
        { id: 14, question: "The new policy will be (  ) next month.", options: ["A. implemented", "B. implied", "C. impoverished", "D. improvised"], correct: 0, explanation: "implement 意为“实施/执行”。" },
        { id: 15, question: "We need to (  ) the contract before signing.", options: ["A. scrutinize", "B. scream", "C. script", "D. scatter"], correct: 0, explanation: "scrutinize 意为“仔细检查”。" },
        { id: 16, question: "He is highly (  ) for the lead developer role.", options: ["A. qualified", "B. quantified", "C. quality", "D. qualifiedly"], correct: 0, explanation: "qualified 意为“有资格的”。" },
        { id: 17, question: "The (  ) of the committee is to oversee the project.", options: ["A. objective", "B. objection", "C. object", "D. objectively"], correct: 0, explanation: "objective 意为“目标”。" },
        { id: 18, question: "Please (  ) that all windows are closed before leaving.", options: ["A. ensure", "B. endure", "C. enlarge", "D. enrich"], correct: 0, explanation: "ensure 意为“确保”。" },
        { id: 19, question: "The company (  ) its employees to take regular breaks.", options: ["A. encourages", "B. encounters", "C. encloses", "D. enforces"], correct: 0, explanation: "encourage 意为“鼓励”。" },
        { id: 20, question: "We have a (  ) deadline for this project.", options: ["A. tight", "B. thin", "C. timid", "D. tidy"], correct: 0, explanation: "tight deadline 意为“紧张的截止日期”。" },
        { id: 21, question: "The company will (  ) a press release later today.", options: ["A. issue", "B. island", "C. isoloate", "D. issue"], correct: 0, explanation: "issue a press release 意为“发布新闻稿”。" },
        { id: 22, question: "We are currently (  ) new talent for our sales team.", options: ["A. recruiting", "B. recovering", "C. recording", "D. reconciling"], correct: 0, explanation: "recruit talent 意为“招聘人才”。" },
        { id: 23, question: "Please (  ) the reception desk upon your arrival.", options: ["A. notify", "B. notice", "C. notion", "D. notch"], correct: 0, explanation: "notify 意为“通知/告知”。" },
        { id: 24, question: "He has a lot of (  ) in the field of international trade.", options: ["A. expertise", "B. expense", "C. expectation", "D. expansion"], correct: 0, explanation: "expertise 意为“专业知识/专门技术”。" },
        { id: 25, question: "The board of directors will (  ) the proposal next week.", options: ["A. deliberate", "B. deliver", "C. delight", "D. delegate"], correct: 0, explanation: "deliberate 意为“商讨/审议”。" },
        { id: 26, question: "We need to (  ) the workspace to improve efficiency.", options: ["A. reorganize", "B. recognize", "C. realize", "D. receive"], correct: 0, explanation: "reorganize 意为“重组/重新整理”。" },
        { id: 27, question: "The employee handbook (  ) the company's code of conduct.", options: ["A. outlines", "B. outlaws", "C. outlets", "D. outlooks"], correct: 0, explanation: "outline 意为“概述”。" },
        { id: 28, question: "She was (  ) for her outstanding performance this year.", options: ["A. commended", "B. commanded", "C. commenced", "D. commented"], correct: 0, explanation: "commend 意为“表扬/称赞”。" },
        { id: 29, question: "The meeting will (  ) at 10 AM sharp.", options: ["A. commence", "B. commerce", "C. comment", "D. commute"], correct: 0, explanation: "commence 意为“开始”。" },
        { id: 30, question: "We need to (  ) the contract to include the new terms.", options: ["A. amend", "B. amount", "C. amuse", "D. amaze"], correct: 0, explanation: "amend 意为“修订”。" },
        { id: 31, question: "The (  ) process should be fair and transparent.", options: ["A. appraisal", "B. appraise", "C. apply", "D. applaud"], correct: 0, explanation: "performance appraisal 意为“绩效评估”。" },
        { id: 32, question: "He is the (  ) candidate for the promotion.", options: ["A. ideal", "B. idea", "C. idol", "D. idle"], correct: 0, explanation: "ideal candidate 意为“理想人选”。" },
        { id: 33, question: "We have (  ) the conference room for the afternoon.", options: ["A. reserved", "B. reversed", "C. revolved", "D. revealed"], correct: 0, explanation: "reserve 意为“预订”。" },
        { id: 34, question: "The project requires (  ) between different departments.", options: ["A. collaboration", "B. collection", "C. collision", "D. collation"], correct: 0, explanation: "collaboration 意为“协作”。" },
        { id: 35, question: "Please (  ) your signature at the bottom of the form.", options: ["A. affix", "B. affect", "C. afford", "D. affirm"], correct: 0, explanation: "affix 意为“盖（印）、签（名）”。" },
        { id: 36, question: "The (  ) for the seminar is attached to this email.", options: ["A. brochure", "B. branch", "C. breed", "D. brief"], correct: 0, explanation: "brochure 意为“小册子”。" },
        { id: 37, question: "We need to (  ) the effectiveness of the training program.", options: ["A. assess", "B. assert", "C. assign", "D. assist"], correct: 0, explanation: "assess 意为“评估”。" },
        { id: 38, question: "The manager gave a (  ) presentation about the new quarterly goals.", options: ["A. succinct", "B. success", "C. succeed", "D. suction"], correct: 0, explanation: "succinct 意为“简洁的”。" },
        { id: 39, question: "The (  ) flow in the office needs to be improved.", options: ["A. workflow", "B. workaholic", "C. workmanship", "D. workshop"], correct: 0, explanation: "workflow 意为“工作流”。" },
        { id: 40, question: "She (  ) the CEO in all administrative matters.", options: ["A. assists", "B. asserts", "C. assigns", "D. assumes"], correct: 0, explanation: "assist 意为“协助”。" },
        { id: 41, question: "The company (  ) its success to its dedicated employees.", options: ["A. attributes", "B. attracts", "C. attempts", "D. attends"], correct: 0, explanation: "attribute sth to sth 意为“把某事归因于某事”。" },
        { id: 42, question: "Please (  ) the meeting minutes to all participants.", options: ["A. circulate", "B. circumscribe", "C. circumstance", "D. circumvent"], correct: 0, explanation: "circulate 意为“传阅/发行”。" },
        { id: 43, question: "The (  ) of the committee is to review all proposals.", options: ["A. mandate", "B. manager", "C. manner", "D. mansion"], correct: 0, explanation: "mandate 意为“授权/委任”。" },
        { id: 44, question: "We need to (  ) for any potential conflicts of interest.", options: ["A. check", "B. chess", "C. cheap", "D. cheat"], correct: 0, explanation: "check for 意为“检查”。" },
        { id: 45, question: "The (  ) for the position includes a competitive salary.", options: ["A. compensation", "B. competition", "C. composition", "D. compilation"], correct: 0, explanation: "compensation 意为“薪酬/补偿”。" },
        { id: 46, question: "He has a (  ) record of achieving results.", options: ["A. proven", "B. proud", "C. price", "D. private"], correct: 0, explanation: "proven record 意为“经证明的记录”。" },
        { id: 47, question: "The (  ) between the two departments has improved.", options: ["A. coordination", "B. cooperation", "C. coalition", "D. collection"], correct: 0, explanation: "coordination 意为“协调”。" },
        { id: 48, question: "Please (  ) that all files are stored securely.", options: ["A. verify", "B. verdict", "C. version", "D. vertical"], correct: 0, explanation: "verify 意为“核实”。" },
        { id: 49, question: "The (  ) of the training session is to enhance skills.", options: ["A. objective", "B. object", "C. objection", "D. objectively"], correct: 0, explanation: "objective 意为“目标”。" },
        { id: 50, question: "The company (  ) its focus on customer service.", options: ["A. emphasized", "B. employed", "C. empowereed", "D. empty"], correct: 0, explanation: "emphasize 意为“强调”。" },
        { id: 51, question: "We need to (  ) the current workflow to save time.", options: ["A. streamline", "B. streamline", "C. street", "D. stress"], correct: 0, explanation: "streamline 意为“精简/使效率更高”。" },
        { id: 52, question: "The (  ) of the meeting was to discuss the budget.", options: ["A. purpose", "B. purchase", "C. purple", "D. pursue"], correct: 0, explanation: "purpose 意为“目的”。" },
        { id: 53, question: "Please (  ) from making personal calls during work hours.", options: ["A. refrain", "B. refresh", "C. reform", "D. refine"], correct: 0, explanation: "refrain from 意为“克制/避免”。" },
        { id: 54, question: "The (  ) provided by the consultant was invaluable.", options: ["A. insight", "B. insight", "C. inside", "D. instead"], correct: 0, explanation: "insight 意为“见解/洞察力”。" },
        { id: 55, question: "We (  ) our gratitude for your hard work.", options: ["A. convey", "B. convert", "C. convict", "D. convene"], correct: 0, explanation: "convey gratitude 意为“传达（感激）”。" },
        { id: 56, question: "The new manager is (  ) for the entire project.", options: ["A. responsible", "B. responsive", "C. restricted", "D. respected"], correct: 0, explanation: "responsible for 意为“负责……”。" },
        { id: 57, question: "We should (  ) the possibility of expanding overseas.", options: ["A. explore", "B. exploit", "C. export", "D. expect"], correct: 0, explanation: "explore 意为“探索/研究（可能性）”。" },
        { id: 58, question: "The (  ) of the survey will be shared next week.", options: ["A. findings", "B. finishes", "C. fingers", "D. figures"], correct: 0, explanation: "findings 意为“调查结果”。" },
        { id: 59, question: "We need to (  ) additional resources for this task.", options: ["A. deploy", "B. defy", "C. denial", "D. destroy"], correct: 0, explanation: "deploy 意为“部署/利用”。" },
        { id: 60, question: "The company has a (  ) reputation in the industry.", options: ["A. stellar", "B. steel", "C. still", "D. story"], correct: 0, explanation: "stellar reputation 意为“卓越的声誉”。" }
    ],
    finance: [
        { id: 1, question: "The company's (  ) has increased significantly this quarter.", options: ["A. revenue", "B. reverse", "C. review", "D. reveal"], correct: 0, explanation: "revenue 意为“收入/营收”。" },
        { id: 2, question: "Investors are worried about the (  ) of the market.", options: ["A. volatility", "B. volume", "C. voluntary", "D. voltage"], correct: 0, explanation: "volatility 意为“波动性”。" },
        { id: 3, question: "The bank will (  ) a loan for the new project.", options: ["A. authorize", "B. authority", "C. author", "D. authentic"], correct: 0, explanation: "authorize a loan 意为“批准贷款”。" },
        { id: 4, question: "Please check the (  ) statement for any discrepancies.", options: ["A. billing", "B. building", "C. boiling", "D. balling"], correct: 0, explanation: "billing statement 意为“账单”。" },
        { id: 5, question: "The firm needs to reduce its (  ) costs.", options: ["A. overhead", "B. overcoat", "C. overcome", "D. overlook"], correct: 0, explanation: "overhead costs 意为“运营成本/经常性开支”。" },
        { id: 6, question: "The company's (  ) are expected to rise by 10%.", options: ["A. profits", "B. prophets", "C. profiles", "D. proofs"], correct: 0, explanation: "profits 意为“利润”。" },
        { id: 7, question: "We need to (  ) the budget for the next year.", options: ["A. allocate", "B. allow", "C. allege", "D. ally"], correct: 0, explanation: "allocate the budget 意为“分配预算”。" },
        { id: 8, question: "The (  ) rate is subject to change without notice.", options: ["A. interest", "B. interesting", "C. intern", "D. internal"], correct: 0, explanation: "interest rate 意为“利率”。" },
        { id: 9, question: "The accountant is (  ) the financial records.", options: ["A. auditing", "B. adding", "C. aiding", "D. aiming"], correct: 0, explanation: "auditing 意为“审计”。" },
        { id: 10, question: "The (  ) of the merger are still being discussed.", options: ["A. terms", "B. teams", "C. themes", "D. times"], correct: 0, explanation: "terms of the merger 意为“合并条款”。" },
        { id: 11, question: "The company decided to (  ) its stock from the exchange.", options: ["A. withdraw", "B. within", "C. without", "D. withstand"], correct: 0, explanation: "withdraw 意为“撤回”。" },
        { id: 12, question: "We have seen a (  ) growth in the tech sector.", options: ["A. stable", "B. staple", "C. stablely", "D. status"], correct: 0, explanation: "stable growth 意为“稳定增长”。" },
        { id: 13, question: "The financial (  ) predicted a market downturn.", options: ["A. analyst", "B. analysis", "C. analyze", "D. analytic"], correct: 0, explanation: "analyst 意为“分析师”。" },
        { id: 14, question: "He needs to (  ) his debt as soon as possible.", options: ["A. liquidate", "B. liquid", "C. limited", "D. listened"], correct: 0, explanation: "liquidate debt 意为“偿清债务”。" },
        { id: 15, question: "The company reported a (  ) half-year result.", options: ["A. deficit", "B. defeat", "C. defect", "D. define"], correct: 0, explanation: "deficit 意为“赤字/亏损”。" },
        { id: 16, question: "The (  ) of the investment is 5%.", options: ["A. yield", "B. yell", "C. yard", "D. yolk"], correct: 0, explanation: "yield 意为“产金/收益率”。" },
        { id: 17, question: "The (  ) value of the property has increased.", options: ["A. market", "B. mark", "C. maker", "D. matter"], correct: 0, explanation: "market value 意为“市场价值”。" },
        { id: 18, question: "The bank will (  ) your account if you don't pay.", options: ["A. freeze", "B. free", "C. fresh", "D. freed"], correct: 0, explanation: "freeze account 意为“冻结账户”。" },
        { id: 19, question: "The (  ) of the project is estimated at $1 million.", options: ["A. expenditure", "B. expense", "C. expand", "D. expedition"], correct: 0, explanation: "expenditure 意为“开支/支出”。" },
        { id: 20, question: "We need to (  ) the risks involved.", options: ["A. evaluate", "B. evolve", "C. evade", "D. evoke"], correct: 0, explanation: "evaluate risks 意为“评估风险”。" },
        { id: 21, question: "The (  ) of the company depends on its investors.", options: ["A. solvency", "B. solution", "C. solitude", "D. solidarity"], correct: 0, explanation: "solvency 意为“偿付能力”。" },
        { id: 22, question: "We need to (  ) for the upcoming financial audit.", options: ["A. prepare", "B. prevent", "C. predict", "D. preserve"], correct: 0, explanation: "prepare 意为“准备”。" },
        { id: 23, question: "The (  ) report showed a net loss for the year.", options: ["A. fiscal", "B. final", "C. fixed", "D. flat"], correct: 0, explanation: "fiscal report 意为“年度财政报告”。" },
        { id: 24, question: "The investment (  ) includes both stocks and bonds.", options: ["A. portfolio", "B. portion", "C. portal", "D. portrait"], correct: 0, explanation: "portfolio 意为“投资组合”。" },
        { id: 25, question: "We need to (  ) our assets to minimize risk.", options: ["A. diversify", "B. divide", "C. divert", "D. divulge"], correct: 0, explanation: "diversify 意为“多样化”。" },
        { id: 26, question: "The (  ) rate has stayed relatively low this year.", options: ["A. inflation", "B. inflated", "C. inflat", "D. inflating"], correct: 0, explanation: "inflation rate 意为“通货膨胀率”。" },
        { id: 27, question: "The company's (  ) are listed on the balance sheet.", options: ["A. liabilities", "B. limits", "C. links", "D. lines"], correct: 0, explanation: "liabilities 意为“负债”。" },
        { id: 28, question: "We are seeking (  ) to fund our technology expansion.", options: ["A. capital", "B. cap", "C. captain", "D. captured"], correct: 0, explanation: "capital 意为“资本/资金”。" },
        { id: 29, question: "The (  ) of the trade agreement is still being finalized.", options: ["A. execution", "B. exercise", "C. excellent", "D. exceed"], correct: 0, explanation: "execution 意为“执行/履行”。" },
        { id: 30, question: "The bank offers a (  ) interest rate for savings accounts.", options: ["A. competitive", "B. competence", "C. compete", "D. competition"], correct: 0, explanation: "competitive 意为“有竞争力的”。" },
        { id: 31, question: "We need to (  ) our spending to stay within budget.", options: ["A. monitor", "B. monkey", "C. mount", "D. morning"], correct: 0, explanation: "monitor 意为“监控/监测”。" },
        { id: 32, question: "The company's (  ) increased by 20% in the last quarter.", options: ["A. valuation", "B. vanity", "C. vanilla", "D. vacancy"], correct: 0, explanation: "valuation 意为“估值”。" },
        { id: 33, question: "He is an expert in (  ) management.", options: ["A. asset", "B. assertive", "C. assess", "D. assent"], correct: 0, explanation: "asset management 意为“资产管理”。" },
        { id: 34, question: "The (  ) from the sale will be used for research.", options: ["A. proceeds", "B. processes", "C. programs", "D. problems"], correct: 0, explanation: "proceeds 意为“所得/收入”。" },
        { id: 35, question: "We need to (  ) the contract with the supplier.", options: ["A. renegotiate", "B. renew", "C. rental", "D. render"], correct: 0, explanation: "renegotiate 意为“重新谈判”。" },
        { id: 36, question: "The financial (  ) are required for the tax filing.", options: ["A. disclosures", "B. discovery", "C. discussions", "D. discounts"], correct: 0, explanation: "disclosures 意为“披露”。" },
        { id: 37, question: "The company has a strong (  ) of cash.", options: ["A. reserve", "B. respect", "C. result", "D. rescue"], correct: 0, explanation: "reserve of cash 意为“现金储备”。" },
        { id: 38, question: "We need to (  ) the productivity of each department.", options: ["A. maximize", "B. maximum", "C. mix", "D. modify"], correct: 0, explanation: "maximize 意为“使增加到最大限度”。" },
        { id: 39, question: "The (  ) of the company is under scrutiny.", options: ["A. integrity", "B. internal", "C. intrest", "D. instinct"], correct: 0, explanation: "integrity 意为“诚信”。" },
        { id: 40, question: "We aim for a (  ) return on our investments.", options: ["A. substantial", "B. submerge", "C. subsist", "D. subtile"], correct: 0, explanation: "substantial return 意为“丰厚的回报”。" },
        { id: 41, question: "The bank will (  ) the transaction within 24 hours.", options: ["A. process", "B. proceed", "C. proclaim", "D. prohibit"], correct: 0, explanation: "process transaction 意为“处理交易”。" },
        { id: 42, question: "We need to (  ) for the potential loss.", options: ["A. compensate", "B. compliment", "C. complex", "D. compile"], correct: 0, explanation: "compensate 意为“补偿”。" },
        { id: 43, question: "The (  ) of the currency has dropped.", options: ["A. value", "B. valid", "C. valley", "D. variant"], correct: 0, explanation: "value 意为“价值”。" },
        { id: 44, question: "Investors are (  ) to see the latest audit report.", options: ["A. anxious", "B. ancient", "C. angle", "D. animal"], correct: 0, explanation: "anxious 意为“渴望的/忧虑的”。" },
        { id: 45, question: "The (  ) of the loan is fixed at 4%.", options: ["A. rate", "B. rare", "C. rain", "D. rail"], correct: 0, explanation: "interest rate 意为“利率”。" },
        { id: 46, question: "We need to (  ) our financial records for the board.", options: ["A. consolidate", "B. consider", "C. construct", "D. consume"], correct: 0, explanation: "consolidate 意为“合并/整合（财务报表等）”。" },
        { id: 47, question: "The (  ) of the stock market is unpredictable.", options: ["A. fluctuation", "B. fluidity", "C. flashlight", "D. flow"], correct: 0, explanation: "fluctuation 意为“波动/起伏”。" },
        { id: 48, question: "The (  ) for the project has been approved.", options: ["A. funding", "B. finding", "C. fading", "D. feeding"], correct: 0, explanation: "funding 意为“资金/拨款”。" },
        { id: 49, question: "We must (  ) the terms of the agreement.", options: ["A. uphold", "B. uphold", "C. uphill", "D. uphold"], correct: 0, explanation: "uphold the terms 意为“维护/遵守条款”。" },
        { id: 50, question: "The (  ) growth of the economy is positive.", options: ["A. exponential", "B. expensive", "C. expense", "D. expend"], correct: 0, explanation: "exponential growth 意为“指数级增长”。" },
        { id: 51, question: "The (  ) is responsible for managing the investment fund.", options: ["A. trustee", "B. trust", "C. truth", "D. truck"], correct: 0, explanation: "trustee 意为“受托人/理事”。" },
        { id: 52, question: "We need to (  ) our taxes by the deadline.", options: ["A. file", "B. fill", "C. film", "D. find"], correct: 0, explanation: "file taxes 意为“申报税务”。" },
        { id: 53, question: "The company reported a (  ) in sales this year.", options: ["A. decline", "B. decide", "C. declare", "D. decode"], correct: 0, explanation: "decline 意为“下降”。" },
        { id: 54, question: "The (  ) value of the company is $10 billion.", options: ["A. market", "B. mark", "C. maker", "D. master"], correct: 0, explanation: "market value 意为“市值”。" },
        { id: 55, question: "We are (  ) with a new partner to expand our market.", options: ["A. collaborating", "B. colliding", "C. collecting", "D. collapsing"], correct: 0, explanation: "collaborate 意为“协作/合作”。" },
        { id: 56, question: "The (  ) of the project is dependent on funding.", options: ["A. feasibility", "B. feature", "C. fever", "D. feather"], correct: 0, explanation: "feasibility 意为“可行性”。" },
        { id: 57, question: "We need to (  ) the contract with the client.", options: ["A. execute", "B. exceed", "C. excise", "D. excuse"], correct: 0, explanation: "execute contract 意为“执行/签署合同”。" },
        { id: 58, question: "The (  ) that we received from the investment was significant.", options: ["A. dividend", "B. division", "C. divide", "D. divine"], correct: 0, explanation: "dividend 意为“股息/红利”。" },
        { id: 59, question: "The company is (  ) a new business strategy.", options: ["A. pursuing", "B. pushing", "C. pulling", "D. punching"], correct: 0, explanation: "pursue strategy 意为“追求/执行策略”。" },
        { id: 60, question: "The (  ) are checked regularly to ensure compliance.", options: ["A. ledgers", "B. legends", "C. letters", "D. levels"], correct: 0, explanation: "ledger 意为“账簿”。" }
    ],
    travel: [
        { id: 1, question: "Your flight has been (  ) due to bad weather.", options: ["A. delayed", "B. deleted", "C. delivered", "D. delighted"], correct: 0, explanation: "flight delayed 意为“航班延误”。" },
        { id: 2, question: "Please have your (  ) ready for inspection.", options: ["A. passport", "B. password", "C. passage", "D. passion"], correct: 0, explanation: "passport 意为“护照”。" },
        { id: 3, question: "The hotel offers a complimentary (  ) service to the airport.", options: ["A. shuttle", "B. shutter", "C. shuffle", "D. shallow"], correct: 0, explanation: "shuttle service 意为“接驳服务”。" },
        { id: 4, question: "Please confirm your (  ) at least 24 hours before departure.", options: ["A. reservation", "B. resolution", "C. reputation", "D. regulation"], correct: 0, explanation: "reservation 意为“预订”。" },
        { id: 5, question: "The (  ) allowance for this flight is 23kg.", options: ["A. baggage", "B. budget", "C. bandage", "D. badge"], correct: 0, explanation: "baggage allowance 意为“行李额度”。" },
        { id: 6, question: "We need to (  ) at the airport three hours early.", options: ["A. check in", "B. check up", "C. check out", "D. check off"], correct: 0, explanation: "check in 意为“办理登机/入住”。" },
        { id: 7, question: "The (  ) passed through the cabin to check seatbelts.", options: ["A. attendant", "B. attention", "C. attendance", "D. attitude"], correct: 0, explanation: "flight attendant 意为“空乘人员”。" },
        { id: 8, question: "I'd like to (  ) an aisle seat if possible.", options: ["A. request", "B. require", "C. repeat", "D. report"], correct: 0, explanation: "request 意为“请求/要求”。" },
        { id: 9, question: "The (  ) for the trip was very tight.", options: ["A. itinerary", "B. item", "C. internal", "D. interest"], correct: 0, explanation: "itinerary 意为“行程表”。" },
        { id: 10, question: "The hotel is (  ) located near the train station.", options: ["A. conveniently", "B. confidently", "C. constantly", "D. consistently"], correct: 0, explanation: "conveniently located 意为“地理位置优越/便利”。" },
        { id: 11, question: "We can (  ) your stay if you need more time.", options: ["A. extend", "B. extent", "C. extra", "D. external"], correct: 0, explanation: "extend stay 意为“延长停留”。" },
        { id: 12, question: "The (  ) to the city center takes about 40 minutes.", options: ["A. commute", "B. command", "C. common", "D. commune"], correct: 0, explanation: "commute 意为“通勤/路径”。" },
        { id: 13, question: "Please present your (  ) pass at the gate.", options: ["A. boarding", "B. boasting", "C. borrowing", "D. bordering"], correct: 0, explanation: "boarding pass 意为“登机牌”。" },
        { id: 14, question: "The hotel (  ) are top-notch, including a spa.", options: ["A. amenities", "B. amendments", "C. amounts", "D. amusements"], correct: 0, explanation: "amenities 意为“便利设施”。" },
        { id: 15, question: "We were (  ) to business class.", options: ["A. upgraded", "B. updated", "C. uprooted", "D. upstaged"], correct: 0, explanation: "be upgraded to 意为“被提升到（更高级别）”。" },
        { id: 16, question: "The (  ) are clearly marked in the terminal.", options: ["A. departures", "B. depends", "C. defeats", "D. details"], correct: 0, explanation: "departures 意为“离港/出发区”。" },
        { id: 17, question: "I need to (  ) my currency before the trip.", options: ["A. exchange", "B. exclude", "C. exceed", "D. excuse"], correct: 0, explanation: "exchange currency 意为“兑换货币”。" },
        { id: 18, question: "The (  ) in the city is very efficient.", options: ["A. transit", "B. translate", "C. transfer", "D. transmit"], correct: 0, explanation: "transit 意为“交通/运输”。" },
        { id: 19, question: "You can find (  ) parking near the entrance.", options: ["A. designated", "B. designed", "C. delighted", "D. deposited"], correct: 0, explanation: "designated parking 意为“指定的停车位”。" },
        { id: 20, question: "The (  ) of the flight was smooth.", options: ["A. duration", "B. durable", "C. during", "D. duress"], correct: 0, explanation: "duration 意为“时长”。" },
        { id: 21, question: "You should (  ) your hotel reservation at least two days in advance.", options: ["A. cancel", "B. canal", "C. cancer", "D. candle"], correct: 0, explanation: "cancel reservation 意为“取消预订”。" },
        { id: 22, question: "The duty-free shop is located in the (  ) area.", options: ["A. departure", "B. depend", "C. defeat", "D. detail"], correct: 0, explanation: "departure area 意为“离港区”。" },
        { id: 23, question: "Please (  ) from using electronic devices during takeoff.", options: ["A. refrain", "B. refresh", "C. reform", "D. refine"], correct: 0, explanation: "refrain from 意为“克制/避免”。" },
        { id: 24, question: "The airline provides (  ) meals for passengers with dietary restrictions.", options: ["A. specialized", "B. special", "C. spatial", "D. spacious"], correct: 1, explanation: "special meals 意为“特殊餐食”。" },
        { id: 25, question: "We need to (  ) our car at the rental agency.", options: ["A. return", "B. retain", "C. retard", "D. retire"], correct: 0, explanation: "return car 意为“还车”。" },
        { id: 26, question: "The (  ) rate for the hotel has increased for the peak season.", options: ["A. occupancy", "B. occupation", "C. occurrence", "D. ocean"], correct: 0, explanation: "occupancy rate 意为“入住率”。" },
        { id: 27, question: "Please (  ) your seat to the upright position.", options: ["A. adjust", "B. adjunct", "C. adjourn", "D. admit"], correct: 0, explanation: "adjust seat 意为“调整座椅”。" },
        { id: 28, question: "The (  ) between the two cities is about 500 miles.", options: ["A. distance", "B. distant", "C. distinct", "D. distress"], correct: 0, explanation: "distance 意为“距离”。" },
        { id: 29, question: "We need to (  ) for the customs declaration.", options: ["A. queue", "B. query", "C. queen", "D. quest"], correct: 0, explanation: "queue 意为“排队”。" },
        { id: 30, question: "The (  ) information is displayed on the overhead monitors.", options: ["A. flight", "B. fight", "C. flighty", "D. fighter"], correct: 0, explanation: "flight information 意为“航班信息”。" },
        { id: 31, question: "The hotel (  ) was very helpful with our luggage.", options: ["A. concierge", "B. concert", "C. concept", "D. concern"], correct: 0, explanation: "concierge 意为“礼宾人员”。" },
        { id: 32, question: "I'd like to (  ) for a room with a sea view.", options: ["A. inquire", "B. injure", "C. inhale", "D. inject"], correct: 0, explanation: "inquire 意为“询问”。" },
        { id: 33, question: "The (  ) to the museum is included in the tour package.", options: ["A. admission", "B. admit", "C. admiring", "D. admiral"], correct: 0, explanation: "admission 意为“入场费/门票”。" },
        { id: 34, question: "Please (  ) your valuables in the hotel safe.", options: ["A. deposit", "B. deport", "C. depict", "D. depend"], correct: 0, explanation: "deposit 意为“寄存/存放”。" },
        { id: 35, question: "The (  ) for the international flight starts in 30 minutes.", options: ["A. boarding", "B. boating", "C. boring", "D. boasting"], correct: 0, explanation: "boarding 意为“登机”。" },
        { id: 36, question: "We (  ) a tour of the historic district.", options: ["A. booked", "B. backed", "C. baked", "D. barked"], correct: 0, explanation: "book a tour 意为“预订行程”。" },
        { id: 37, question: "The (  ) was delayed due to a mechanical issue.", options: ["A. departure", "B. depend", "C. detail", "D. defeat"], correct: 0, explanation: "departure 意为“出发/起飞”。" },
        { id: 38, question: "Please (  ) that you have all your belongings before leaving.", options: ["A. verify", "B. verdict", "C. version", "D. vertical"], correct: 0, explanation: "verify 意为“核实/确认”。" },
        { id: 39, question: "The (  ) to the island is available only by boat.", options: ["A. access", "B. accept", "C. accent", "D. account"], correct: 0, explanation: "access 意为“进入/通道”。" },
        { id: 40, question: "The airline (  ) its policy on carry-on luggage.", options: ["A. modified", "B. modern", "C. modest", "D. model"], correct: 0, explanation: "modify 意为“修改/更改”。" },
        { id: 41, question: "Please (  ) your seat for landing.", options: ["A. secure", "B. second", "C. secret", "D. section"], correct: 0, explanation: "secure 意为“系好/固定”。" },
        { id: 42, question: "The (  ) for the flight is approximately 2 hours.", options: ["A. duration", "B. during", "C. durable", "D. duress"], correct: 0, explanation: "duration 意为“时长”。" },
        { id: 43, question: "We recommend purchasing travel (  ) for international trips.", options: ["A. insurance", "B. instance", "C. inside", "D. instead"], correct: 0, explanation: "travel insurance 意为“旅游保险”。" },
        { id: 44, question: "The hotel (  ) include a gym and a swimming pool.", options: ["A. facilities", "B. factors", "C. faculties", "D. facets"], correct: 0, explanation: "facilities 意为“设施”。" },
        { id: 45, question: "Please (  ) from bringing liquids onto the airplane.", options: ["A. refrain", "B. refresh", "C. reform", "D. refine"], correct: 0, explanation: "refrain from 意为“克制/避免”。" },
        { id: 46, question: "The (  ) for the tour is subject to change.", options: ["A. itinerary", "B. iteration", "C. item", "D. idiom"], correct: 0, explanation: "itinerary 意为“行程表”。" },
        { id: 47, question: "We (  ) our hotel room through a travel agent.", options: ["A. booked", "B. baked", "C. backed", "D. barked"], correct: 0, explanation: "book 意为“预订”。" },
        { id: 48, question: "The (  ) was very smooth despite the turbulence.", options: ["A. landing", "B. ending", "C. sending", "D. lending"], correct: 0, explanation: "landing 意为“降落”。" },
        { id: 49, question: "Please (  ) your passport to the immigration officer.", options: ["A. present", "B. pretend", "C. prevent", "D. prevent"], correct: 0, explanation: "present 意为“出示”。" },
        { id: 50, question: "The (  ) in the business lounge is excellent.", options: ["A. hospitality", "B. hospital", "C. hostile", "D. hostline"], correct: 0, explanation: "hospitality 意为“款待/招待”。" },
        { id: 51, question: "We need to (  ) our currency at the exchange bureau.", options: ["A. convert", "B. convent", "C. convex", "D. convoy"], correct: 0, explanation: "convert currency 意为“兑换货币”。" },
        { id: 52, question: "The (  ) of the journey was pleasant.", options: ["A. remainder", "B. remain", "C. reminder", "D. removal"], correct: 0, explanation: "remainder 意为“剩余部分”。" },
        { id: 53, question: "Please (  ) that your luggage is properly tagged.", options: ["A. ensure", "B. endure", "C. enrich", "D. enlarge"], correct: 0, explanation: "ensure 意为“确保”。" },
        { id: 54, question: "The (  ) to the city center is very frequent.", options: ["A. shuttle", "B. shuffle", "C. shutter", "D. shallow"], correct: 0, explanation: "shuttle 意为“穿梭班车”。" },
        { id: 55, question: "We received a (  ) upgrade to a suite.", options: ["A. complementary", "B. complex", "C. complaint", "D. comply"], correct: 0, explanation: "complementary 意为“赠送的/免费的”。" },
        { id: 56, question: "The (  ) was delayed due to technical difficulties.", options: ["A. departure", "B. depend", "C. detail", "D. defeat"], correct: 0, explanation: "departure 意为“出发/离港”。" },
        { id: 57, question: "Please (  ) your seatbelt during the flight.", options: ["A. fasten", "B. faster", "C. fashion", "D. fasten"], correct: 0, explanation: "fasten seatbelt 意为“系好安全带”。" },
        { id: 58, question: "The (  ) are clearly marked in the arrivals hall.", options: ["A. exits", "B. edits", "C. extra", "D. exams"], correct: 0, explanation: "exits 意为“出口”。" },
        { id: 59, question: "We need to (  ) for a visa before we travel.", options: ["A. apply", "B. apple", "C. apply", "D. apply"], correct: 0, explanation: "apply for a visa 意为“申请签证”。" },
        { id: 60, question: "The (  ) provides a spectacular view of the mountains.", options: ["A. destination", "B. destiny", "C. design", "D. detail"], correct: 0, explanation: "destination 意为“目的地”。" }
    ],
    tech: [
        { id: 1, question: "The software requires a mandatory (  ) to fix the security bug.", options: ["A. update", "B. upstart", "C. upright", "D. uproot"], correct: 0, explanation: "software update 意为“软件更新”。" },
        { id: 2, question: "Our (  ) infrastructure is being upgraded.", options: ["A. network", "B. notebook", "C. netizen", "D. nowhere"], correct: 0, explanation: "network infrastructure 意为“网络基础设施”。" },
        { id: 3, question: "The new system is (  ) with older versions.", options: ["A. compatible", "B. comparable", "C. competitive", "D. comfortable"], correct: 0, explanation: "compatible with 意为“兼容”。" },
        { id: 4, question: "We need to (  ) our data to the cloud.", options: ["A. migrate", "B. mitigate", "C. militate", "D. mistake"], correct: 0, explanation: "migrate data 意为“迁移数据”。" },
        { id: 5, question: "The (  ) is responsible for maintaining the servers.", options: ["A. administrator", "B. administration", "C. admin", "D. admissible"], correct: 0, explanation: "administrator 意为“管理员”。" },
        { id: 6, question: "Please (  ) the latest version of the application.", options: ["A. install", "B. instant", "C. instead", "D. instance"], correct: 0, explanation: "install 意为“安装”。" },
        { id: 7, question: "The (  ) settings can be adjusted in the menu.", options: ["A. configuration", "B. congregation", "C. confirmation", "D. conformation"], correct: 0, explanation: "configuration 意为“配置”。" },
        { id: 8, question: "We are experiencing a (  ) in the server room.", options: ["A. malfunction", "B. maltreat", "C. malnutrition", "D. malformed"], correct: 0, explanation: "malfunction 意为“故障”。" },
        { id: 9, question: "The data (  ) ensures that files are not lost.", options: ["A. redundancy", "B. reduction", "C. redaction", "D. redemption"], correct: 0, explanation: "data redundancy 意为“数据冗余/备份”。" },
        { id: 10, question: "Users must use a (  ) password.", options: ["A. robust", "B. robot", "C. roast", "D. rodent"], correct: 0, explanation: "robust password 意为“强健的密码”。" },
        { id: 11, question: "The (  ) of the website is very user-friendly.", options: ["A. interface", "B. interference", "C. interferon", "D. interlude"], correct: 0, explanation: "interface 意为“界面”。" },
        { id: 12, question: "We need to (  ) the potential security threats.", options: ["A. neutralize", "B. nurture", "C. notice", "D. number"], correct: 0, explanation: "neutralize threats 意为“消除/中和威胁”。" },
        { id: 13, question: "The (  ) speed of the internet is 100 Mbps.", options: ["A. transmission", "B. transition", "C. translation", "D. transaction"], correct: 0, explanation: "transmission speed 意为“传输速度”。" },
        { id: 14, question: "He is an expert in (  ) intelligence.", options: ["A. artificial", "B. artisan", "C. article", "D. artful"], correct: 0, explanation: "artificial intelligence 意为“人工智能”。" },
        { id: 15, question: "The (  ) code is stored in the repository.", options: ["A. source", "B. sauce", "C. sound", "D. south"], correct: 0, explanation: "source code 意为“源代码”。" },
        { id: 16, question: "We need to (  ) the server before it crashes.", options: ["A. reboot", "B. rebound", "C. rebirth", "D. rebuild"], correct: 0, explanation: "reboot 意为“重启”。" },
        { id: 17, question: "The (  ) layer provides extra security.", options: ["A. encryption", "B. encouragement", "C. encroachment", "D. encumbrance"], correct: 0, explanation: "encryption 意为“加密”。" },
        { id: 18, question: "The (  ) process takes several hours.", options: ["A. compilation", "B. compassion", "C. competition", "D. compilation"], correct: 0, explanation: "compilation 意为“编译”。" },
        { id: 19, question: "We need to (  ) the system for any vulnerabilities.", options: ["A. patch", "B. path", "C. part", "D. past"], correct: 0, explanation: "patch the system 意为“给系统打补丁”。" },
        { id: 20, question: "The (  ) of the database is optimized.", options: ["A. performance", "B. perfection", "C. permanent", "D. perspective"], correct: 0, explanation: "performance 意为“性能”。" },
        { id: 21, question: "We need to set up a (  ) to prevent unauthorized access.", options: ["A. firewall", "B. firework", "C. firefly", "D. fireproof"], correct: 0, explanation: "firewall 意为“防火墙”。" },
        { id: 22, question: "The system is capable of (  ) high volumes of traffic.", options: ["A. handling", "B. handing", "C. hanging", "D. hinting"], correct: 0, explanation: "handle traffic 意为“处理流量”。" },
        { id: 23, question: "Please (  ) the data to ensure accuracy.", options: ["A. validate", "B. variable", "C. vanish", "D. vacuum"], correct: 0, explanation: "validate data 意为“验证数据”。" },
        { id: 24, question: "Our (  ) services are hosted on AWS.", options: ["A. cloud", "B. cold", "C. cord", "D. card"], correct: 0, explanation: "cloud services 意为“云服务”。" },
        { id: 25, question: "The developers are working on a new (  ) for the mobile app.", options: ["A. feature", "B. feather", "C. fever", "D. fender"], correct: 0, explanation: "feature 意为“功能/特性”。" },
        { id: 26, question: "We need to (  ) the files into a single archive.", options: ["A. compress", "B. complex", "C. complain", "D. comply"], correct: 0, explanation: "compress files 意为“压缩文件”。" },
        { id: 27, question: "The (  ) between the two systems is seamless.", options: ["A. integration", "B. intention", "C. interaction", "D. interference"], correct: 0, explanation: "integration 意为“集成/整合”。" },
        { id: 28, question: "The (  ) allows users to reset their own passwords.", options: ["A. portal", "B. porter", "C. portion", "D. portrait"], correct: 0, explanation: "portal 意为“门户/入口”。" },
        { id: 29, question: "We found a (  ) that was causing the crash.", options: ["A. bug", "B. bag", "C. big", "D. bog"], correct: 0, explanation: "bug 意为“程序漏洞/缺陷”。" },
        { id: 30, question: "The (  ) of the project is estimated at three months.", options: ["A. timeline", "B. timeout", "C. title", "D. tissue"], correct: 0, explanation: "timeline 意为“时间轴/工期”。" },
        { id: 31, question: "We need to (  ) the hardware every five years.", options: ["A. replace", "B. replay", "C. replace", "D. repel"], correct: 0, explanation: "replace hardware 意为“更换硬件”。" },
        { id: 32, question: "The (  ) is used to store temporary data.", options: ["A. cache", "B. cash", "C. case", "D. cage"], correct: 0, explanation: "cache 意为“缓存”。" },
        { id: 33, question: "Please (  ) your changes to the repository.", options: ["A. commit", "B. command", "C. comment", "D. common"], correct: 0, explanation: "commit changes 意为“提交更改”。" },
        { id: 34, question: "The (  ) of the network is very high.", options: ["A. bandwidth", "B. bandage", "C. bandit", "D. banquet"], correct: 0, explanation: "bandwidth 意为“带宽”。" },
        { id: 35, question: "The (  ) is responsible for the overall design of the software.", options: ["A. architect", "B. archive", "C. article", "D. artisan"], correct: 0, explanation: "architect 意为“架构师”。" },
        { id: 36, question: "We need to (  ) the server logs to find the error.", options: ["A. analyze", "B. analogy", "C. anonymize", "D. antagonize"], correct: 0, explanation: "analyze logs 意为“分析日志”。" },
        { id: 37, question: "The (  ) provides a way to interact with the database.", options: ["A. query", "B. queen", "C. quest", "D. queer"], correct: 0, explanation: "query 意为“查询”。" },
        { id: 38, question: "The (  ) determines how the data is stored.", options: ["A. schema", "B. scheme", "C. schedule", "D. scenario"], correct: 0, explanation: "schema 意为“架构/模式（尤指数据库）”。" },
        { id: 39, question: "We need to (  ) the system to ensure it's still working.", options: ["A. monitor", "B. money", "C. monk", "D. mountain"], correct: 0, explanation: "monitor system 意为“监控系统”。" },
        { id: 40, question: "The (  ) is used to connect multiple devices together.", options: ["A. switch", "B. swing", "C. swim", "D. swift"], correct: 0, explanation: "switch 意为“交换机”。" },
        { id: 41, question: "We need to (  ) the system for any signs of performance degradation.", options: ["A. monitor", "B. monument", "C. monetize", "D. monastery"], correct: 0, explanation: "monitor 意为“监控”。" },
        { id: 42, question: "The (  ) provides a common way for different applications to communicate.", options: ["A. API", "B. APP", "C. APK", "D. APU"], correct: 0, explanation: "API (Application Programming Interface) 意为“应用程序接口”。" },
        { id: 43, question: "The data (  ) is critical for protecting sensitive information.", options: ["A. encryption", "B. enactment", "C. enlistment", "D. enrichment"], correct: 0, explanation: "encryption 意为“加密”。" },
        { id: 44, question: "We are (  ) a new feature to the existing platform.", options: ["A. deploying", "B. defying", "C. denying", "D. decaying"], correct: 0, explanation: "deploy 意为“部署/发布”。" },
        { id: 45, question: "The (  ) process should be thoroughly documented.", options: ["A. installation", "B. instigation", "C. insulation", "D. inspiration"], correct: 0, explanation: "installation 意?为“安装”。" },
        { id: 46, question: "The (  ) of the server has reached its limit.", options: ["A. capacity", "B. capillary", "C. capitalism", "D. captivity"], correct: 0, explanation: "capacity 意为“容量”。" },
        { id: 47, question: "We need to (  ) the code before it can be executed.", options: ["A. compile", "B. complain", "C. comply", "D. complete"], correct: 0, explanation: "compile 意为“编译”。" },
        { id: 48, question: "The (  ) is used to track changes in the source code.", options: ["A. repository", "B. reposition", "C. repose", "D. report"], correct: 0, explanation: "repository 意为“仓库”。" },
        { id: 49, question: "Users can (  ) their files to the remote server.", options: ["A. upload", "B. uphold", "C. upright", "D. uproot"], correct: 0, explanation: "upload 意为“上传”。" },
        { id: 50, question: "The (  ) provides a secure way to access the company network.", options: ["A. VPN", "B. VIP", "C. VAT", "D. VCR"], correct: 0, explanation: "VPN (Virtual Private Network) 意为“虚拟专用网络”。" },
        { id: 51, question: "We need to (  ) the database to improve query speed.", options: ["A. index", "B. indent", "C. infect", "D. inform"], correct: 0, explanation: "index 意为“索引”。" },
        { id: 52, question: "The (  ) of the system is checked every hour.", options: ["A. integrity", "B. intensely", "C. intent", "D. internal"], correct: 0, explanation: "integrity 意为“完整性”。" },
        { id: 53, question: "The (  ) is responsible for designing- the user interface.", options: ["A. designer", "B. desert", "C. desire", "D. destiny"], correct: 0, explanation: "designer 意为“设计师”。" },
        { id: 54, question: "We found a (  ) in the security protocols.", options: ["A. vulnerability", "B. volunteer", "C. vocational", "D. voluntary"], correct: 0, explanation: "vulnerability 意为“漏洞”。" },
        { id: 55, question: "The (  ) of the software is expected to take two weeks.", options: ["A. development", "B. deviation", "C. devotion", "D. device"], correct: 0, explanation: "development 意为“开发”。" },
        { id: 56, question: "We need to (  ) the system to the cloud.", options: ["A. migrate", "B. mitigate", "C. militate", "D. moderate"], correct: 0, explanation: "migrate 意为“迁移”。" },
        { id: 57, question: "The (  ) is used to store data locally.", options: ["A. storage", "B. storm", "C. story", "D. stock"], correct: 0, explanation: "storage 意为“存储”。" },
        { id: 58, question: "We are (  ) the new system to ensure it's bug-free.", options: ["A. testing", "B. tasting", "C. teasing", "D. tending"], correct: 0, explanation: "testing 意为“测试”。" },
        { id: 59, question: "The (  ) between the two devices is established.", options: ["A. connection", "B. connotation", "C. connection", "D. consensus"], correct: 0, explanation: "connection 意为“连接”。" },
        { id: 60, question: "The (  ) of the project is overseen by the CTO.", options: ["A. architecture", "B. archive", "C. arcane", "D. arsenal"], correct: 0, explanation: "architecture 意为“架构”。" },
        { id: 61, question: "We need to (  ) the system for any potential bottlenecks.", options: ["A. analyze", "B. anatomy", "C. analogy", "D. anatomy"], correct: 0, explanation: "analyze 意为“分析”。" },
        { id: 62, question: "The (  ) ensures that data is consistent across all nodes.", options: ["A. synchronization", "B. synonym", "C. synopsis", "D. syndicate"], correct: 0, explanation: "synchronization 意为“同步”。" },
        { id: 63, question: "Please (  ) the latest security patches to the server.", options: ["A. apply", "B. apple", "C. apple", "D. apply"], correct: 0, explanation: "apply patches 意为“应用补丁”。" },
        { id: 64, question: "The (  ) between the front-end and back-end is critical.", options: ["A. communication", "B. commission", "C. commotion", "D. commodity"], correct: 0, explanation: "communication 意为“通信/沟通”。" },
        { id: 65, question: "We are (  ) the database to handle millions of records.", options: ["A. optimizing", "B. optional", "C. opinion", "D. optical"], correct: 0, explanation: "optimize 意为“优化”。" },
        { id: 66, question: "The (  ) is used to load balance the traffic.", options: ["A. balancer", "B. ballad", "C. ballot", "D. balance"], correct: 0, explanation: "load balancer 意为“负载均衡器”。" },
        { id: 67, question: "We need to (  ) the code regularly to avoid technical debt.", options: ["A. refactor", "B. reform", "C. reflux", "D. refract"], correct: 0, explanation: "refactor 意为“重构”。" },
        { id: 68, question: "The (  ) provides a way to store data in a structured way.", options: ["A. database", "B. dataset", "C. datagram", "D. datable"], correct: 0, explanation: "database 意为“数据库”。" },
        { id: 69, question: "Users can (  ) their profile information in the settings.", options: ["A. modify", "B. modern", "C. modest", "D. model"], correct: 0, explanation: "modify 意为“修改”。" },
        { id: 70, question: "The (  ) of the application is responsive on all devices.", options: ["A. layout", "B. layer", "C. lawyer", "D. layout"], correct: 0, explanation: "layout 意为“布局”。" },
        { id: 71, question: "We need to (  ) the system for any signs of intrusion.", options: ["A. scan", "B. scam", "C. scan", "D. scarf"], correct: 0, explanation: "scan 意为“扫描”。" },
        { id: 72, question: "The (  ) process ensures that the software is reliable.", options: ["A. validation", "B. vacation", "C. vacation", "D. validation"], correct: 0, explanation: "validation 意为“验证”。" },
        { id: 73, question: "Please (  ) the logs to find the root cause of the error.", options: ["A. examine", "B. example", "C. exhaust", "D. exhibit"], correct: 0, explanation: "examine 意为“检查/审查”。" },
        { id: 74, question: "The (  ) specifies how the system should behave.", options: ["A. requirement", "B. request", "C. record", "D. respect"], correct: 0, explanation: "requirement 意为“需求/要求”。" },
        { id: 75, question: "We are (  ) a new version of the API.", options: ["A. launching", "B. lunching", "C. laughing", "D. launching"], correct: 0, explanation: "launch 意为“发布/启动”。" },
        { id: 76, question: "The (  ) layer handles all the business logic.", options: ["A. application", "B. appliance", "C. applause", "D. applicant"], correct: 0, explanation: "application layer 意为“应用层”。" },
        { id: 77, question: "We need to (  ) the system for any performance issues.", options: ["A. profile", "B. profit", "C. profile", "D. program"], correct: 0, explanation: "profile 意为“性能分析”。" },
        { id: 78, question: "The (  ) is used to cache frequently accessed data.", options: ["A. cache", "B. cash", "C. case", "D. cage"], correct: 0, explanation: "cache 意为“缓存”。" },
        { id: 79, question: "We are (  ) the legacy code to the new framework.", options: ["A. porting", "B. parting", "C. porting", "D. posting"], correct: 0, explanation: "port 意为“移植”。" },
        { id: 80, question: "The (  ) of the network is monitored in real-time.", options: ["A. performance", "B. perfection", "C. performance", "D. perspective"], correct: 0, explanation: "performance 意为“性能”。" }
    ]
};
